//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourcesToTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourcesToTest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.SourcesToTest", typeof(SourcesToTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources
        ///{
        ///   public class AvoidAssignmentsInSubExpressions_Source
        ///   {
        ///      class Test
        ///      {
        ///         public Test(String str) {
        ///
        ///         }
        ///         public void AMethod(String str) {
        ///
        ///         }
        ///
        ///         public void BMethod(String str1, String str2) {
        ///
        ///         }
        ///      }
        ///
        ///      public void AssignmentsInSubExpressionsKO() {
        ///         Str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidAssignmentsInSubExpressions_Source {
            get {
                return ResourceManager.GetString("AvoidAssignmentsInSubExpressions_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;   
        ///using System.Threading.Tasks;
        ///
        ///namespace Sonar.Analyzers.CSharp.Common.Tests.UnitTests.Analyzers.AvoidClassesWithTooManyConstructors
        ///{
        ///    class AvoidClassesWithTooManyConstructors_QualUatExample
        ///    {
        ///        public AvoidClassesWithTooManyConstructors_QualUatExample()
        ///        {
        ///            //1er constructeur
        ///        }
        ///
        ///        public AvoidClassesWithTooManyConstructors_QualUatExample(string maChaine)
        ///        {
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidClassesWithTooManyConstructors_QualUatExample {
            get {
                return ResourceManager.GetString("AvoidClassesWithTooManyConstructors_QualUatExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Dynamic;
        ///
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class AvoidCreatingExceptionWithoutThrowingThem_Source {
        ///
        ///      private NullReferenceException _nullReferenceExceptionNotThrown = new NullReferenceException();
        ///      private NullReferenceException _nullReferenceExceptionThrown = new NullReferenceException();
        ///
        ///      private void ThrowNullReferenceException()  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidCreatingExceptionWithoutThrowingThem_Source {
            get {
                return ResourceManager.GetString("AvoidCreatingExceptionWithoutThrowingThem_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.ComponentModel.Composition;
        ///using System.ComponentModel.Design;
        ///
        ///
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///
        ///   namespace Shared
        ///   {
        ///      interface IInterface1
        ///      {
        ///
        ///      }
        ///
        ///      interface IInterface2
        ///      {
        ///
        ///      }
        ///
        ///      interface IInterface3
        ///      {
        ///
        ///      }
        ///
        ///      interface IInterface4
        ///      {
        ///
        ///      }
        ///
        ///      interface IInterface5
        ///      {
        ///
        ///      }
        ///
        ///      interface IInterface6
        ///      {
        ///
        ///      }
        ///
        ///      interface IInterface7
        ///      {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidCreatingNewInstanceOfSharedInstance_Source {
            get {
                return ResourceManager.GetString("AvoidCreatingNewInstanceOfSharedInstance_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class AvoidEmptyFinalizers_Source {
        ///
        ///      class FinalizerWithDebugFailInIfDebugKO {
        ///         ~FinalizerWithDebugFailInIfDebugKO() {
        ///#if DEBUG
        ///            Debug.Fail(&quot;Failed&quot;);
        ///#endif
        ///         }
        ///      }
        ///
        ///      class FinalizerInIfDebugWithDebugFailOK {
        ///#if DEBUG
        ///         ~FinalizerInIfDebugWithDebugF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidEmptyFinalizers_Source {
            get {
                return ResourceManager.GetString("AvoidEmptyFinalizers_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   class AvoidLocalVariablesShadowingClassFields_Source {
        ///      class Shadow {
        ///         private int aMember;
        ///
        ///         void Shadow_aMemberKO() {
        ///            int aMember = 0;
        ///         }
        ///
        ///         void Shadow_aMemberInInnerScopeKO() {
        ///            {
        ///               int aMember = 0;
        ///            }
        ///         }
        ///
        ///         void DontShadow_aMemberOK() {
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidLocalVariablesShadowingClassFields_Source {
            get {
                return ResourceManager.GetString("AvoidLocalVariablesShadowingClassFields_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   class AvoidLocalVariablesShadowingClassFields_Source {
        ///      class Shadow {
        ///         private int aMember;
        ///
        ///         void Shadow_aMemberKO() {
        ///            int aMember = 0;
        ///         }
        ///
        ///         void Shadow_aMemberInInnerScopeKO() {
        ///            {
        ///               int aMember = 0;
        ///            }
        ///         }
        ///
        ///         void DontShadow_aMemberOK() {
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidLocalVariablesShadowingClassFields_Source1 {
            get {
                return ResourceManager.GetString("AvoidLocalVariablesShadowingClassFields_Source1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Threading;
        ///
        ///
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class AvoidMethodsNamedWithoutFollowingSynchronousAsynchronousConvention_Source {
        ///
        ///    public Task Read(byte [] buffer, int offset, int count, CancellationToken cancellationToken) 
        ///    {
        ///        Action&lt;object&gt; action = (object obj) =&gt;
        ///                        {
        ///                           Console.WriteLin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidMethodsNamedWithoutFollowingSynchronousAsynchronousConvention_Source {
            get {
                return ResourceManager.GetString("AvoidMethodsNamedWithoutFollowingSynchronousAsynchronousConvention_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class AvoidRecursiveTypeInheritance_Source {
        ///
        ///      class C1&lt;T&gt; {
        ///      }
        ///
        ///      class C2KO&lt;S&gt; : C1&lt;C2KO&lt;C1&lt;S&gt;&gt;&gt; // Noncompliant
        ///      {
        ///         public int x = 101;
        ///      }
        ///
        ///      class C3KO&lt;S&gt; : C1&lt;C3KO&lt;C3KO&lt;S&gt;&gt;&gt; // Noncompliant
        ///      {
        ///         public int x = 101;
        ///      }
        ///
        ///      class C4OK&lt;S&gt; : C1&lt;C1&lt;C1&lt;S&gt;&gt;&gt; 
        ///      {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidRecursiveTypeInheritance_Source {
            get {
                return ResourceManager.GetString("AvoidRecursiveTypeInheritance_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Reflection;
        ///
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class AvoidUsing_Assembly_LoadFrom_Assembly_LoadFileAndAssembly_LoadWithPartialName_Source {
        ///
        ///      public class KlassAssemblyLoadFrom {
        ///         public void foo() {
        ///            Assembly SampleAssembly;
        ///            SampleAssembly = Assembly.LoadFrom(&quot;c:\\Sample.Assembly.dll&quot;);
        ///            // Obtain a refe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidUsing_Assembly_LoadFrom_Assembly_LoadFileAndAssembly_LoadWithPartialName_Source {
            get {
                return ResourceManager.GetString("AvoidUsing_Assembly_LoadFrom_Assembly_LoadFileAndAssembly_LoadWithPartialName_Sou" +
                        "rce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class ChildClassFieldsShouldNotShadowParentClassFields_Source {
        ///
        ///      class Base {
        ///         protected int ripe;
        ///         protected int flesh;
        ///      }
        ///
        ///      class Derived : Base {
        ///         private bool ripe; // Noncompliant
        ///         private static int FLESH; // Noncompliant
        ///
        ///         private bool ripened;
        ///         private static char FLESH_COL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChildClassFieldsShouldNotShadowParentClassFields_Source {
            get {
                return ResourceManager.GetString("ChildClassFieldsShouldNotShadowParentClassFields_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class ClassesImplementingIEquatableTShouldBeSealed_Source {
        ///
        ///      public class UnSealedEqualsVirtual : IEquatable&lt;int&gt; {
        ///         public virtual bool Equals(int i) {
        ///            return false;
        ///         }
        ///      }
        ///
        ///      public class UnSealedDerviedFromUnSealedEqualsVirtual : UnSealedEqualsVirtual {
        ///         public override bool E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassesImplementingIEquatableTShouldBeSealed_Source {
            get {
                return ResourceManager.GetString("ClassesImplementingIEquatableTShouldBeSealed_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Globalization;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class CultureDependentStringOperationsShouldSpecifyCulture_Source {
        ///      private static readonly String str = &quot;abc&quot;;
        ///      String lowerKO = str.ToLower();
        ///      String lowerOK = str.ToLower(CultureInfo.InvariantCulture);
        ///      String lowerOKInvariant = str.ToLowerInvariant();
        ///
        ///      String upperKO = st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CultureDependentStringOperationsShouldSpecifyCulture_Source {
            get {
                return ResourceManager.GetString("CultureDependentStringOperationsShouldSpecifyCulture_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class EmptyArraysAndCollectionsShouldBeReturnedInsteadOfNull_Source {
        ///      class Result {
        ///
        ///      }
        ///
        ///      class KO {
        ///         public Result[] GetResultsReturnArray() {
        ///            return null; // Noncompliant
        ///         }
        ///
        ///         public IEnumerable&lt;Result&gt; GetResultsReturnIEnumerable() {
        ///            return null; // Noncomplia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyArraysAndCollectionsShouldBeReturnedInsteadOfNull_Source {
            get {
                return ResourceManager.GetString("EmptyArraysAndCollectionsShouldBeReturnedInsteadOfNull_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Runtime.Serialization;
        ///using System.Security.Permissions;
        ///
        ///namespace UnitTests.UnitTest.Sources
        ///{
        ///
        ///   [Serializable]
        ///   class SerializedKO1 : ISerializable
        ///   {
        ///
        ///      [FileIOPermissionAttribute(SecurityAction.Demand, Unrestricted = true)]
        ///      SerializedKO1() {
        ///      }
        ///
        ///      protected SerializedKO1(SerializationInfo info, StreamingContext context) { // Noncom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnsureConstructorsOfSerializableClassesAreSecure_Source {
            get {
                return ResourceManager.GetString("EnsureConstructorsOfSerializableClassesAreSecure_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class EnsureProperArgumentsToEvents_Source {
        ///
        ///      public class Klass1 {
        ///         public event EventHandler foo;
        ///
        ///         protected virtual void OnTfoo(EventArgs e) {
        ///            foo?.Invoke(null, e); // Violation
        ///         }
        ///      }
        ///
        ///      public class Klass2 {
        ///         public static event EventHandler foo;
        ///
        ///         prote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnsureProperArgumentsToEvents_Source {
            get {
                return ResourceManager.GetString("EnsureProperArgumentsToEvents_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources
        ///{
        ///   public class ForLoopConditionShouldBeInvariant_Source
        ///   {
        ///
        ///      void FuncI(int i) {
        ///         ++i;
        ///      }
        ///
        ///      void ForLoopConditionInvariantOK() {
        ///         for (int i = 0; i &lt; 10; ++i) {
        ///            FuncI(i);
        ///         }
        ///
        ///         for (int i = 0; i &lt; 10; ++i) {
        ///            Console.WriteLine(i);
        ///         }
        ///
        ///         int j =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForLoopConditionShouldBeInvariant_Source {
            get {
                return ResourceManager.GetString("ForLoopConditionShouldBeInvariant_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class InheritedMemberVisibilityShouldNotBeDecreased_Source {
        ///
        ///      public class Base {
        ///         public virtual void VirtualMethod() { }
        ///         public void BaseMethod(int x) { }
        ///      }
        ///
        ///      public class Foo  : Base {
        ///         public override void VirtualMethod() { }
        ///         public void SomeMethod(int count) { }
        ///         p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InheritedMemberVisibilityShouldNotBeDecreased_Source {
            get {
                return ResourceManager.GetString("InheritedMemberVisibilityShouldNotBeDecreased_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class InterfaceInstancesShouldNotBeCastToConcreteTypes_Source {
        ///      interface BaseInterface {
        ///         void BaseInterfaceMethod();
        ///      }
        ///
        ///      interface DerivedInterface : BaseInterface {
        ///         void DerivedInterfaceMethod();
        ///      }
        ///
        ///      abstract class AbstractClass : DerivedInterface {
        ///         public abstract void B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InterfaceInstancesShouldNotBeCastToConcreteTypes_Source {
            get {
                return ResourceManager.GetString("InterfaceInstancesShouldNotBeCastToConcreteTypes_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources
        ///{
        ///   public class MergeAdjacentTryBlocksWithIdenticalCatchFinallyStatements_Source
        ///   {
        ///      void DoFirstThing() { }
        ///
        ///      void DoSecondThing() { }
        ///
        ///      void DoThirdThing() { }
        ///
        ///      void DoFourthThing() { }
        ///
        ///      void DoThingInCatch() { }
        ///
        ///      void TryIdenticalCatchKO() {
        ///         try {
        ///            DoFirstThing();
        ///
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MergeAdjacentTryBlocksWithIdenticalCatchFinallyStatements_Source {
            get {
                return ResourceManager.GetString("MergeAdjacentTryBlocksWithIdenticalCatchFinallyStatements_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Immutable;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class MutableStaticFieldsOfTypeCollectionOrArrayShouldNotBePublicStatic_Source {
        ///
        ///      public class AClass {
        ///         public static string[] strings1KO = { &quot;first&quot;, &quot;second&quot; };  // Noncompliant
        ///         public static List&lt;String&gt; strings2KO = new List&lt;String [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MutableStaticFieldsOfTypeCollectionOrArrayShouldNotBePublicStatic_Source {
            get {
                return ResourceManager.GetString("MutableStaticFieldsOfTypeCollectionOrArrayShouldNotBePublicStatic_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources
        ///{
        ///   public class RecursionShouldNotBeInfinite_Source
        ///   {
        ///
        ///      //int PowKO16(int num, int exponent)   // Noncompliant; no condition under which pow isn&apos;t re-called
        ///      //{
        ///      //   switch (num) {
        ///      //      case 1:
        ///      //         try {
        ///      //            try {
        ///      //               if (10 &lt; exponent) {
        ///      //               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecursionShouldNotBeInfinite_Source {
            get {
                return ResourceManager.GetString("RecursionShouldNotBeInfinite_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class TrackFIXMETags_Source {
        ///      // FIXME
        ///      // FIXME too.
        ///      // NOT FIXME
        ///      /* FIXME Again */
        ///      /* Not Fixme */
        ///      /* fixme */
        ///   }
        ///}
        ///.
        /// </summary>
        internal static string TrackFIXMETags_Source {
            get {
                return ResourceManager.GetString("TrackFIXMETags_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class TrackTODOTags_Source {
        ///      //TODO this
        ///      // TODO that
        ///      // Not TODO
        ///      /* TODO this again */
        ///      /*todo THAT again*/
        ///      /* NOT TODO */
        ///
        ///      /// TODO &lt;summary&gt;
        ///      /// 
        ///      /// &lt;/summary&gt;
        ///      void Test() {
        ///
        ///      }
        ///   }
        ///}
        ///.
        /// </summary>
        internal static string TrackTODOTags_Source {
            get {
                return ResourceManager.GetString("TrackTODOTags_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace UnitTests.UnitTest.Sources {
        ///   public class UseLogicalORInsteadOfBitwiseORInBooleanContext_Source {
        ///
        ///      private bool ReturnTrue() {
        ///         return true;
        ///      }
        ///
        ///      private bool ReturnFalse() {
        ///         return false;
        ///      }
        ///
        ///      private int Return1() {
        ///         return 1;
        ///      }
        ///
        ///      private int Return0() {
        ///         return 0;
        ///      }
        ///
        ///      publ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UseLogicalORInsteadOfBitwiseORInBooleanContext_Source {
            get {
                return ResourceManager.GetString("UseLogicalORInsteadOfBitwiseORInBooleanContext_Source", resourceCulture);
            }
        }
    }
}
